### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by aaronbeekay** [spirilis/mcp2515#3]
This driver looks very handy and I’d like to use it in one of the projects I’m tinkering with at work. But I can’t do that at the moment because no license is specified in the project.

Would you consider releasing the code under the MIT or Apache-2.0 licenses?

**Comment by kaspar030** [comment]
@spirilis please respond to this. I'd also like to use this code. My plan is to integrate it into the RIOT OS as a package. We'd also need some statement regarding the license.

**Comment by spirilis** [comment]
fyi- just logged into github and noticed this.  I'll add a license to it, stand by.

**Comment by spirilis** [comment]
Done.

**Comment by aaronbeekay** [comment]
@spirilis that project turned into dusty history, but thanks so much for following up on a vintage request!
